# Este arquivo serve para definir as variaveis de ambiente utilizadas
# pela aplicaçao para o ambiente de desenvolvimento. Exemplo:
# TEST_DATABASE_USERNAME: travis
# S3_BUCKET_NAME: ...
# AWS_ACCESS_KEY_ID: ...
# AWS_SECRET_ACCESS_KEY: ...
#MYSQL_SOCKET_PATH: /var/run/mysqld/mysqld.sock