# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a08872fed77a544cec859f2fa5f6d4df220ff0bc89ed26ba08d4b7f881e0f24a8a943f7001b00d015fe212d204886bc4bc72786c817b6fa7c0801408f408fb9

test:
  secret_key_base: 25198fd171facd2b7f921c4bf938eebc668aca57050b9cfa0d6b2aa0bf69bd9021789dd5b92289b25f25631123c69634fe939a81393aaef19ba9b77f6f693621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
